import React from "react";
import styled from "styled-components";
import { motion } from "framer-motion";
import Center from "../images/rezzsha.png"
import Team from "../images/team 1.png"
import Bottom from "../images/section-2.png"
const Section2=()=>{

    return(
   <Container>
      {/* <Img2 src={Bottom}/> */}
        <h1>ITSUKI PARTY</h1>  
            <TextBox>

            Each ITSUKI NFT is algorithmically generated by combining 272+ unique traits with varying rarity across categories.
            </TextBox>
            <Img  src={Team}/>
          
      

    </Container>

    );
}
export default Section2;
const Container= styled.div`
display:flex;


flex-direction:column;
border:solid green 4px;
margin-top:400px;
h1{
margin-left:600px;    
    position:absolute;
    color:white;
    font-family:'Poppins';
   
    font-size:90px;
    @media(max-width:786px){
        font-size:30px;
        }
        @media(max-width:480px){
        fontsize:20px;
        }
}

`;

const Text=styled.div`

width: 750px;
height: 483px;
left: 103px;


text-align:left;


font-family:'Poppins';
h2{
    color:white;
    font-size: 42px;
    line-height: 63px;
}
h4{
    color:white;
    font-weight:100;
    font-size:20px;
    line-height: 35px;
}

@media (max-width: 768px) {
    width:400px;
    h2{
        font-size:24px;
    }
    h4{
        font-size:18px;
    }
    font-size:30px;
  }
  @media (max-width: 480px) {
    width:200px;
    font-size:15px;
  }
`;
const TextBox=styled.div`
font-size:32px;
margin:300px 220px;
color:white;
font-family:'Poppins';
position:absolute;
text-align: center;
@media (max-width: 768px) {
  
   font-size:12px;
   margin:10px 10px;
  }
  @media (max-width: 480px) {
font-size:12px;

text-align:center;
margin:10px 10px;
  }
`;
const Img=styled.img`

width:60px:
position:absolute;
display:block;
max-width:100%;
margin-top:800px;

`;

const Img2=styled.img`
position:absolute;
display:block;
max-width:100%;
margin-top:-620px;
@media (max-width: 768px) {
    display:block;
    height:auto;
    
  }
  @media (max-width: 480px) {
    display:block;
    height:auto;
  }

`;